# Generated by Django 3.2.7 on 2021-11-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='s_icon',
            field=models.ImageField(default='photos/default_photo.png', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='img',
            field=models.ImageField(default='image/default_goods.png', upload_to='image'),
        ),
    ]
